
global:
  scrape_interval: 10s

rule_files:
    - prometheus_rules.yml

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs: 
      - targets: ['192.168.150.4:9100'] 
